"""
ts-manager: compile and install Neovim treesitter parsers and queries.

Usage:
    uv run ts_manager/main.py install [lang ...]
    uv run ts_manager/main.py update  [lang ...]
    uv run ts_manager/main.py status  [lang ...]
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import tomllib
import urllib.request
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).parent.parent
CONFIG_FILE = PROJECT_ROOT / "config.toml"
LOCK_FILE = PROJECT_ROOT / "lock.toml"
CLONE_DIR = PROJECT_ROOT / ".cache" / "grammars"

PARSER_DIR = Path.home() / ".local" / "share" / "nvim" / "site" / "parser"
QUERY_DIR = Path.home() / ".local" / "share" / "nvim" / "site" / "queries"

QUERY_TYPES = ["highlights", "indents", "folds", "injections", "locals"]

# ---------------------------------------------------------------------------
# Config / lock helpers
# ---------------------------------------------------------------------------


def load_config() -> dict:
    with CONFIG_FILE.open("rb") as f:
        return tomllib.load(f)


def load_lock() -> dict:
    if not LOCK_FILE.exists():
        return {}
    with LOCK_FILE.open("rb") as f:
        data = tomllib.load(f)
    return data.get("languages", {})


def save_lock(lock: dict) -> None:
    lines = ["# Auto-generated by ts-manager. Commit this file to reproduce your parser versions.\n"]
    for lang, info in sorted(lock.items()):
        lines.append(f"[languages.{lang}]\n")
        lines.append(f'tag = "{info["tag"]}"\n')
        lines.append(f'commit = "{info["commit"]}"\n')
        lines.append("\n")
    LOCK_FILE.write_text("".join(lines))


# ---------------------------------------------------------------------------
# Neovim ABI detection
# ---------------------------------------------------------------------------


def detect_nvim_abi() -> int:
    try:
        result = subprocess.run(
            ["nvim", "--headless", "-c", "lua io.write(tostring(vim.treesitter.language_version))", "-c", "q"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return int(result.stdout.strip())
    except Exception as e:
        print(f"  warning: could not detect Neovim ABI ({e}), defaulting to 14")
        return 14


def detect_nvim_runtime_paths() -> list[Path] | None:
    try:
        result = subprocess.run(
            ["nvim", "--headless", "-c", "lua io.write(vim.json.encode(vim.api.nvim_list_runtime_paths()))", "-c", "q"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            stderr = result.stderr.strip() or result.stdout.strip() or "unknown error"
            raise RuntimeError(stderr)
        return [Path(path).resolve() for path in json.loads(result.stdout)]
    except Exception as e:
        print(f"  warning: could not detect Neovim runtimepath ({e})")
        return None


def warn_if_parser_dir_missing_from_runtimepath() -> None:
    runtime_paths = detect_nvim_runtime_paths()
    if runtime_paths is None:
        return

    parser_runtime_root = PARSER_DIR.parent.resolve()
    if parser_runtime_root not in runtime_paths:
        print(
            "  warning: PARSER_DIR parent is not on Neovim's runtimepath; "
            f"parsers installed to {PARSER_DIR} may not be discovered"
        )
        print(f"           expected runtime path entry: {parser_runtime_root}")


# ---------------------------------------------------------------------------
# Tag resolution
# ---------------------------------------------------------------------------

_SEMVER_RE = re.compile(r"refs/tags/(v?\d+\.\d+[\.\d]*)$")


def get_latest_tag(repo_url: str) -> tuple[str, str]:
    """Return (tag, commit) for the latest semver tag, or ('HEAD', commit) if none."""
    result = subprocess.run(
        ["git", "ls-remote", "--tags", "--sort=-v:refname", repo_url],
        capture_output=True,
        text=True,
        timeout=30,
    )
    for line in result.stdout.splitlines():
        # Skip peeled tag objects (^{})
        if line.endswith("^{}"):
            continue
        commit, ref = line.split("\t", 1)
        m = _SEMVER_RE.match(ref)
        if m:
            return m.group(1), commit.strip()

    # No semver tags — fall back to HEAD
    head = subprocess.run(
        ["git", "ls-remote", repo_url, "HEAD"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if head.stdout:
        commit = head.stdout.split()[0]
        return "HEAD", commit.strip()

    raise RuntimeError(f"Could not resolve any ref for {repo_url}")


# ---------------------------------------------------------------------------
# Clone / update
# ---------------------------------------------------------------------------


def clone_or_update(repo_url: str, dest: Path, tag: str) -> None:
    if not dest.exists():
        ref = tag if tag != "HEAD" else "HEAD"
        args = ["git", "clone", "--depth", "1"]
        if tag != "HEAD":
            args += ["--branch", tag]
        args += [repo_url, str(dest)]
        _run(args, f"Cloning {repo_url} @ {tag}")
    else:
        # Fetch the desired tag/ref and check it out
        _run(["git", "-C", str(dest), "fetch", "--depth", "1", "origin", tag], f"Fetching {tag}")
        _run(["git", "-C", str(dest), "checkout", "FETCH_HEAD"], "Checking out")


def _run(args: list[str], label: str) -> None:
    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"{label} failed:\n{result.stderr.strip()}")


# ---------------------------------------------------------------------------
# Parser compilation
# ---------------------------------------------------------------------------


def ensure_parser_c(grammar_dir: Path) -> None:
    if not (grammar_dir / "src" / "parser.c").exists():
        print("  src/parser.c missing, running tree-sitter generate...")
        result = subprocess.run(
            ["tree-sitter", "generate"],
            cwd=grammar_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"tree-sitter generate failed:\n{result.stderr.strip()}")


def compile_parser(grammar_dir: Path, lang: str, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / f"{lang}.so"

    if shutil.which("tree-sitter"):
        result = subprocess.run(
            ["tree-sitter", "build", "--output", str(out), str(grammar_dir)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"tree-sitter build failed:\n{result.stderr.strip()}")
    else:
        # Fallback: invoke gcc directly
        src_dir = grammar_dir / "src"
        sources = [str(src_dir / "parser.c")]
        scanner_c = src_dir / "scanner.c"
        scanner_cc = src_dir / "scanner.cc"

        compiler = "gcc"
        extra = []
        if scanner_cc.exists():
            # Mixed C/C++ — compile scanner separately then link
            scanner_obj = src_dir / "scanner.o"
            _run(
                ["g++", "-shared", "-fPIC", "-O2", "-c", str(scanner_cc), "-o", str(scanner_obj)],
                "Compiling C++ scanner",
            )
            extra = [str(scanner_obj)]
        elif scanner_c.exists():
            sources.append(str(scanner_c))

        _run(
            [compiler, "-shared", "-fPIC", "-O2", "-I", str(src_dir), *sources, *extra, "-o", str(out)],
            f"Compiling {lang} with gcc",
        )


# ---------------------------------------------------------------------------
# Query installation
# ---------------------------------------------------------------------------


def fetch_queries_from_repo(queries_repo: str, lang: str, dest: Path) -> list[str]:
    """
    Fetch query files from a GitHub repo specified as "owner/repo@ref".
    Downloads directly via the raw.githubusercontent.com URL.
    Returns list of installed query type names.
    """
    repo, _, ref = queries_repo.partition("@")
    ref = ref or "master"
    base = f"https://raw.githubusercontent.com/{repo}/{ref}/queries/{lang}"

    dest.mkdir(parents=True, exist_ok=True)
    installed = []
    for qt in QUERY_TYPES:
        url = f"{base}/{qt}.scm"
        try:
            with urllib.request.urlopen(url, timeout=10) as resp:
                if resp.status == 200:
                    (dest / f"{qt}.scm").write_bytes(resp.read())
                    installed.append(qt)
        except urllib.error.HTTPError:
            pass  # file doesn't exist for this language, skip silently
    return installed


def install_queries(grammar_dir: Path, lang: str, query_dest_root: Path, repo_root: Path | None = None) -> None:
    src = grammar_dir / "queries"
    # Some repos (e.g. tree-sitter-typescript) keep queries at the repo root
    # rather than inside the grammar subdirectory.
    if not src.is_dir() and repo_root is not None:
        src = repo_root / "queries"
    if not src.is_dir():
        print(f"  warning: no queries/ directory found in {grammar_dir}")
        return

    dest = query_dest_root / lang
    dest.mkdir(parents=True, exist_ok=True)

    installed = []
    for qt in QUERY_TYPES:
        src_file = src / f"{qt}.scm"
        if src_file.exists():
            shutil.copy2(src_file, dest / f"{qt}.scm")
            installed.append(qt)

    if installed:
        print(f"  queries: {', '.join(installed)}")
    else:
        print(f"  warning: no .scm files found in {src}")


# ---------------------------------------------------------------------------
# Core install logic
# ---------------------------------------------------------------------------


def install_language(lang: str, cfg: dict, lock: dict, force: bool, abi: int) -> dict | None:
    """
    Install or update a single language. Returns updated lock entry, or None if skipped.
    """
    repo = cfg["repo"]
    grammar_path = cfg.get("grammar_path")
    queries_repo = cfg.get("queries_repo")

    print(f"\n[{lang}]")
    print(f"  resolving latest tag from {repo}...")
    tag, commit = get_latest_tag(repo)
    print(f"  latest: {tag} ({commit[:12]})")

    existing = lock.get(lang, {})
    if not force and existing.get("tag") == tag:
        print("  up to date, skipping")
        return None

    # Repos shared across multiple grammar_path entries are cloned once
    # under a key derived from the repo URL.
    repo_key = repo.rstrip("/").rsplit("/", 1)[-1]  # e.g. "tree-sitter-typescript"
    clone_dest = CLONE_DIR / repo_key

    clone_or_update(repo, clone_dest, tag)

    grammar_dir = clone_dest / grammar_path if grammar_path else clone_dest

    ensure_parser_c(grammar_dir)

    print(f"  compiling parser...")
    compile_parser(grammar_dir, lang, PARSER_DIR)
    print(f"  parser -> {PARSER_DIR / (lang + '.so')}")

    dest = QUERY_DIR / lang
    if dest.is_symlink():
        dest.unlink()

    if queries_repo:
        print(f"  fetching queries from {queries_repo}...")
        installed = fetch_queries_from_repo(queries_repo, lang, dest)
        if installed:
            print(f"  queries: {', '.join(installed)}")
        else:
            print(f"  warning: no queries found in {queries_repo} for {lang}")
    else:
        install_queries(grammar_dir, lang, QUERY_DIR, repo_root=clone_dest)

    return {"tag": tag, "commit": commit}


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_install(langs: list[str], config: dict, lock: dict, force: bool = True) -> None:
    abi = detect_nvim_abi()
    print(f"Neovim treesitter ABI: {abi}")
    warn_if_parser_dir_missing_from_runtimepath()
    languages = config.get("languages", {})
    targets = langs or list(languages.keys())

    for lang in targets:
        if lang not in languages:
            print(f"\n[{lang}] unknown language, skipping")
            continue
        result = install_language(lang, languages[lang], lock, force=force, abi=abi)
        if result is not None:
            lock[lang] = result

    save_lock(lock)
    print("\nDone.")


def cmd_update(langs: list[str], config: dict, lock: dict) -> None:
    cmd_install(langs, config, lock, force=False)


def cmd_status(langs: list[str], config: dict, lock: dict) -> None:
    warn_if_parser_dir_missing_from_runtimepath()
    languages = config.get("languages", {})
    targets = langs or list(languages.keys())

    col_w = max(len(l) for l in targets) + 2
    print(f"\n{'LANGUAGE':<{col_w}}  {'INSTALLED':<16}  AVAILABLE")
    print("-" * (col_w + 40))

    for lang in targets:
        if lang not in languages:
            print(f"{lang:<{col_w}}  {'(unknown)'}")
            continue
        installed = lock.get(lang, {}).get("tag", "(none)")
        repo = languages[lang]["repo"]
        try:
            latest, _ = get_latest_tag(repo)
        except Exception:
            latest = "(error)"
        marker = "" if installed == latest else "  *"
        print(f"{lang:<{col_w}}  {installed:<16}  {latest}{marker}")

    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(0)

    command, *rest = args
    config = load_config()
    lock = load_lock()

    match command:
        case "install":
            cmd_install(rest, config, lock, force=True)
        case "update":
            cmd_update(rest, config, lock)
        case "status":
            cmd_status(rest, config, lock)
        case _:
            print(f"Unknown command: {command!r}")
            print("Usage: ts-manager <install|update|status> [lang ...]")
            sys.exit(1)


if __name__ == "__main__":
    main()
